This module provides several classes in support of Joyent\textquotesingle{}s \href{http://www.joyent.com/developers/node/design/errors}{\tt Best Practices for Error Handling in Node.\+js}. If you find any of the behavior here confusing or surprising, check out that document first.

The error classes here support\+:


\begin{DoxyItemize}
\item printf-\/style arguments for the message
\item chains of causes
\item properties to provide extra information about the error
\item creating your own subclasses that support all of these
\end{DoxyItemize}

The classes here are\+:


\begin{DoxyItemize}
\item {\bfseries V\+Error}, for chaining errors while preserving each one\textquotesingle{}s error message. This is useful in servers and command-\/line utilities when you want to propagate an error up a call stack, but allow various levels to add their own context. See examples below.
\item {\bfseries W\+Error}, for wrapping errors while hiding the lower-\/level messages from the top-\/level error. This is useful for A\+PI endpoints where you don\textquotesingle{}t want to expose internal error messages, but you still want to preserve the error chain for logging and debugging.
\item {\bfseries S\+Error}, which is just like V\+Error but interprets printf-\/style arguments more strictly.
\item {\bfseries Multi\+Error}, which is just an Error that encapsulates one or more other errors. (This is used for parallel operations that return several errors.)
\end{DoxyItemize}

\section*{Quick start}

First, install the package\+: \begin{DoxyVerb}npm install verror
\end{DoxyVerb}


If nothing else, you can use V\+Error as a drop-\/in replacement for the built-\/in Java\+Script Error class, with the addition of printf-\/style messages\+:


\begin{DoxyCode}
var err = new VError('missing file: "%s"', '/etc/passwd');
console.log(err.message);
\end{DoxyCode}


This prints\+: \begin{DoxyVerb}missing file: "/etc/passwd"
\end{DoxyVerb}


You can also pass a {\ttfamily cause} argument, which is any other Error object\+:


\begin{DoxyCode}
var fs = require('fs');
var filename = '/nonexistent';
fs.stat(filename, function (err1) \{
    var err2 = new VError(err1, 'stat "%s"', filename);
    console.error(err2.message);
\});
\end{DoxyCode}


This prints out\+: \begin{DoxyVerb}stat "/nonexistent": ENOENT, stat '/nonexistent'
\end{DoxyVerb}


which resembles how Unix programs typically report errors\+: \begin{DoxyVerb}$ sort /nonexistent
sort: open failed: /nonexistent: No such file or directory
\end{DoxyVerb}


To match the Unixy feel, when you print out the error, just prepend the program\textquotesingle{}s name to the V\+Error\textquotesingle{}s {\ttfamily message}. Or just call \href{https://github.com/joyent/node-cmdutil}{\tt node-\/cmdutil.\+fail(your\+\_\+verror)}, which does this for you.

You can get the next-\/level Error using {\ttfamily err.\+cause()}\+:


\begin{DoxyCode}
console.error(err2.cause().message);
\end{DoxyCode}


prints\+: \begin{DoxyVerb}ENOENT, stat '/nonexistent'
\end{DoxyVerb}


Of course, you can chain these as many times as you want, and it works with any kind of Error\+:


\begin{DoxyCode}
var err1 = new Error('No such file or directory');
var err2 = new VError(err1, 'failed to stat "%s"', '/junk');
var err3 = new VError(err2, 'request failed');
console.error(err3.message);
\end{DoxyCode}


This prints\+: \begin{DoxyVerb}request failed: failed to stat "/junk": No such file or directory
\end{DoxyVerb}


The idea is that each layer in the stack annotates the error with a description of what it was doing. The end result is a message that explains what happened at each level.

You can also decorate Error objects with additional information so that callers can not only handle each kind of error differently, but also construct their own error messages (e.\+g., to localize them, format them, group them by type, and so on). See the example below.

\section*{Deeper dive}

The two main goals for V\+Error are\+:


\begin{DoxyItemize}
\item {\bfseries Make it easy to construct clear, complete error messages intended for people.} Clear error messages greatly improve both user experience and debuggability, so we wanted to make it easy to build them. That\textquotesingle{}s why the constructor takes printf-\/style arguments.
\item {\bfseries Make it easy to construct objects with programmatically-\/accessible metadata} (which we call {\itshape informational properties}). Instead of just saying \char`\"{}connection refused while connecting to 192.\+168.\+1.\+2\+:80\char`\"{}, you can add properties like {\ttfamily \char`\"{}ip\char`\"{}\+: \char`\"{}192.\+168.\+1.\+2\char`\"{}} and {\ttfamily \char`\"{}tcp\+Port\char`\"{}\+: 80}. This can be used for feeding into monitoring systems, analyzing large numbers of Errors (as from a log file), or localizing error messages.
\end{DoxyItemize}

To really make this useful, it also needs to be easy to compose Errors\+: higher-\/level code should be able to augment the Errors reported by lower-\/level code to provide a more complete description of what happened. Instead of saying \char`\"{}connection refused\char`\"{}, you can say \char`\"{}operation X failed\+: connection refused\char`\"{}. That\textquotesingle{}s why V\+Error supports {\ttfamily causes}.

In order for all this to work, programmers need to know that it\textquotesingle{}s generally safe to wrap lower-\/level Errors with higher-\/level ones. If you have existing code that handles Errors produced by a library, you should be able to wrap those Errors with a V\+Error to add information without breaking the error handling code. There are two obvious ways that this could break such consumers\+:


\begin{DoxyItemize}
\item The error\textquotesingle{}s name might change. People typically use {\ttfamily name} to determine what kind of Error they\textquotesingle{}ve got. To ensure compatibility, you can create V\+Errors with custom names, but this approach isn\textquotesingle{}t great because it prevents you from representing complex failures. For this reason, V\+Error provides {\ttfamily find\+Cause\+By\+Name}, which essentially asks\+: does this Error {\itshape or any of its causes} have this specific type? If error handling code uses {\ttfamily find\+Cause\+By\+Name}, then subsystems can construct very specific causal chains for debuggability and still let people handle simple cases easily. There\textquotesingle{}s an example below.
\item The error\textquotesingle{}s properties might change. People often hang additional properties off of Error objects. If we wrap an existing Error in a new Error, those properties would be lost unless we copied them. But there are a variety of both standard and non-\/standard Error properties that should {\itshape not} be copied in this way\+: most obviously {\ttfamily name}, {\ttfamily message}, and {\ttfamily stack}, but also {\ttfamily file\+Name}, {\ttfamily line\+Number}, and a few others. Plus, it\textquotesingle{}s useful for some Error subclasses to have their own private properties -- and there\textquotesingle{}d be no way to know whether these should be copied. For these reasons, V\+Error first-\/classes these information properties. You have to provide them in the constructor, you can only fetch them with the {\ttfamily info()} function, and V\+Error takes care of making sure properties from causes wind up in the {\ttfamily info()} output.
\end{DoxyItemize}

Let\textquotesingle{}s put this all together with an example from the node-\/fast R\+PC library. node-\/fast implements a simple R\+PC protocol for \mbox{\hyperlink{classNode}{Node}} programs. There\textquotesingle{}s a server and client interface, and clients make R\+PC requests to servers. Let\textquotesingle{}s say the server fails with an Unauthorized\+Error with message \char`\"{}user \textquotesingle{}bob\textquotesingle{} is not
authorized\char`\"{}. The client wraps all server errors with a Fast\+Server\+Error. The client also wraps all request errors with a Fast\+Request\+Error that includes the name of the R\+PC call being made. The result of this failed R\+PC might look like this\+: \begin{DoxyVerb}name: FastRequestError
message: "request failed: server error: user 'bob' is not authorized"
rpcMsgid: <unique identifier for this request>
rpcMethod: GetObject
cause:
    name: FastServerError
    message: "server error: user 'bob' is not authorized"
    cause:
        name: UnauthorizedError
        message: "user 'bob' is not authorized"
        rpcUser: "bob"
\end{DoxyVerb}


When the caller uses {\ttfamily V\+Error.\+info()}, the information properties are collapsed so that it looks like this\+: \begin{DoxyVerb}message: "request failed: server error: user 'bob' is not authorized"
rpcMsgid: <unique identifier for this request>
rpcMethod: GetObject
rpcUser: "bob"
\end{DoxyVerb}


Taking this apart\+:


\begin{DoxyItemize}
\item The error\textquotesingle{}s message is a complete description of the problem. The caller can report this directly to its caller, which can potentially make its way back to an end user (if appropriate). It can also be logged.
\item The caller can tell that the request failed on the server, rather than as a result of a client problem (e.\+g., failure to serialize the request), a transport problem (e.\+g., failure to connect to the server), or something else (e.\+g., a timeout). They do this using `find\+Cause\+By\+Name(\textquotesingle{}Fast\+Server\+Error'){\ttfamily  rather than checking the}name\`{} field directly.
\item If the caller logs this error, the logs can be analyzed to aggregate errors by cause, by R\+PC method name, by user, or whatever. Or the error can be correlated with other events for the same rpc\+Msgid.
\item It wasn\textquotesingle{}t very hard for any part of the code to contribute to this Error. Each part of the stack has just a few lines to provide exactly what it knows, with very little boilerplate.
\end{DoxyItemize}

It\textquotesingle{}s not expected that you\textquotesingle{}d use these complex forms all the time. Despite supporting the complex case above, you can still just do\+:

new V\+Error(\char`\"{}my service isn\textquotesingle{}t working\char`\"{});

for the simple cases.

\section*{Reference\+: V\+Error, W\+Error, S\+Error}

V\+Error, W\+Error, and S\+Error are convenient drop-\/in replacements for {\ttfamily Error} that support printf-\/style arguments, first-\/class causes, informational properties, and other useful features.

\subsection*{Constructors}

The V\+Error constructor has several forms\+:


\begin{DoxyCode}
/*
 * This is the most general form.  You can specify any supported options
 * (including "cause" and "info") this way.
 */
new VError(options, sprintf\_args...)

/*
 * This is a useful shorthand when the only option you need is "cause".
 */
new VError(cause, sprintf\_args...)

/*
 * This is a useful shorthand when you don't need any options at all.
 */
new VError(sprintf\_args...)
\end{DoxyCode}


All of these forms construct a new V\+Error that behaves just like the built-\/in Java\+Script {\ttfamily Error} class, with some additional methods described below.

In the first form, {\ttfamily options} is a plain object with any of the following optional properties\+:

\tabulinesep=1mm
\begin{longtabu} spread 0pt [c]{*{3}{|X[-1]}|}
\hline
\rowcolor{\tableheadbgcolor}\textbf{ \mbox{\hyperlink{structOption}{Option}} name  }&\textbf{ Type  }&\textbf{ Meaning   }\\\cline{1-3}
\endfirsthead
\hline
\endfoot
\hline
\rowcolor{\tableheadbgcolor}\textbf{ \mbox{\hyperlink{structOption}{Option}} name  }&\textbf{ Type  }&\textbf{ Meaning   }\\\cline{1-3}
\endhead
{\ttfamily name}  &string  &Describes what kind of error this is. This is intended for programmatic use to distinguish between different kinds of errors. Note that in modern versions of Node.\+js, this name is ignored in the {\ttfamily stack} property value, but callers can still use the {\ttfamily name} property to get at it.   \\\cline{1-3}
{\ttfamily cause}  &any Error object  &Indicates that the new error was caused by {\ttfamily cause}. See {\ttfamily cause()} below. If unspecified, the cause will be {\ttfamily null}.   \\\cline{1-3}
{\ttfamily strict}  &boolean  &If true, then {\ttfamily null} and {\ttfamily undefined} values in {\ttfamily sprintf\+\_\+args} are passed through to {\ttfamily sprintf()}. Otherwise, these are replaced with the strings `\textquotesingle{}null'`, and '{\ttfamily undefined}\textquotesingle{}, respectively.   \\\cline{1-3}
{\ttfamily constructor\+Opt}  &function  &If specified, then the stack trace for this error ends at function {\ttfamily constructor\+Opt}. Functions called by {\ttfamily constructor\+Opt} will not show up in the stack. This is useful when this class is subclassed.   \\\cline{1-3}
{\ttfamily info}  &object  &Specifies arbitrary informational properties that are available through the {\ttfamily V\+Error.\+info(err)} static class method. See that method for details.   \\\cline{1-3}
\end{longtabu}


The second form is equivalent to using the first form with the specified {\ttfamily cause} as the error\textquotesingle{}s cause. This form is distinguished from the first form because the first argument is an Error.

The third form is equivalent to using the first form with all default option values. This form is distinguished from the other forms because the first argument is not an object or an Error.

The {\ttfamily W\+Error} constructor is used exactly the same way as the {\ttfamily V\+Error} constructor. The {\ttfamily S\+Error} constructor is also used the same way as the {\ttfamily V\+Error} constructor except that in all cases, the {\ttfamily strict} property is overriden to \`{}true.

\subsection*{Public properties}

{\ttfamily V\+Error}, {\ttfamily W\+Error}, and {\ttfamily S\+Error} all provide the same public properties as Java\+Script\textquotesingle{}s built-\/in Error objects.

\tabulinesep=1mm
\begin{longtabu} spread 0pt [c]{*{3}{|X[-1]}|}
\hline
\rowcolor{\tableheadbgcolor}\textbf{ Property name  }&\textbf{ Type  }&\textbf{ Meaning   }\\\cline{1-3}
\endfirsthead
\hline
\endfoot
\hline
\rowcolor{\tableheadbgcolor}\textbf{ Property name  }&\textbf{ Type  }&\textbf{ Meaning   }\\\cline{1-3}
\endhead
{\ttfamily name}  &string  &Programmatically-\/usable name of the error.   \\\cline{1-3}
{\ttfamily message}  &string  &Human-\/readable summary of the failure. Programmatically-\/accessible details are provided through {\ttfamily V\+Error.\+info(err)} class method.   \\\cline{1-3}
{\ttfamily stack}  &string  &Human-\/readable stack trace where the Error was constructed.   \\\cline{1-3}
\end{longtabu}


For all of these classes, the printf-\/style arguments passed to the constructor are processed with {\ttfamily sprintf()} to form a message. For {\ttfamily W\+Error}, this becomes the complete {\ttfamily message} property. For {\ttfamily S\+Error} and {\ttfamily V\+Error}, this message is prepended to the message of the cause, if any (with a suitable separator), and the result becomes the {\ttfamily message} property.

The {\ttfamily stack} property is managed entirely by the underlying Java\+Script implementation. It\textquotesingle{}s generally implemented using a getter function because constructing the human-\/readable stack trace is somewhat expensive.

\subsection*{Class methods}

The following methods are defined on the {\ttfamily V\+Error} class and as exported functions on the {\ttfamily verror} module. They\textquotesingle{}re defined this way rather than using methods on V\+Error instances so that they can be used on Errors not created with {\ttfamily V\+Error}.

\subsubsection*{{\ttfamily V\+Error.\+cause(err)}}

The {\ttfamily cause()} function returns the next Error in the cause chain for {\ttfamily err}, or {\ttfamily null} if there is no next error. See the {\ttfamily cause} argument to the constructor. Errors can have arbitrarily long cause chains. You can walk the {\ttfamily cause} chain by invoking {\ttfamily V\+Error.\+cause(err)} on each subsequent return value. If {\ttfamily err} is not a {\ttfamily V\+Error}, the cause is {\ttfamily null}.

\subsubsection*{{\ttfamily V\+Error.\+info(err)}}

Returns an object with all of the extra error information that\textquotesingle{}s been associated with this Error and all of its causes. These are the properties passed in using the {\ttfamily info} option to the constructor. Properties not specified in the constructor for this Error are implicitly inherited from this error\textquotesingle{}s cause.

These properties are intended to provide programmatically-\/accessible metadata about the error. For an error that indicates a failure to resolve a D\+NS name, informational properties might include the D\+NS name to be resolved, or even the list of resolvers used to resolve it. The values of these properties should generally be plain objects (i.\+e., consisting only of null, undefined, numbers, booleans, strings, and objects and arrays containing only other plain objects).

\subsubsection*{{\ttfamily V\+Error.\+full\+Stack(err)}}

Returns a string containing the full stack trace, with all nested errors recursively reported as `\textquotesingle{}caused by\+:' + err.\+stack\`{}.

\subsubsection*{{\ttfamily V\+Error.\+find\+Cause\+By\+Name(err, name)}}

The {\ttfamily find\+Cause\+By\+Name()} function traverses the cause chain for {\ttfamily err}, looking for an error whose {\ttfamily name} property matches the passed in {\ttfamily name} value. If no match is found, {\ttfamily null} is returned.

If all you want is to know {\itshape whether} there\textquotesingle{}s a cause (and you don\textquotesingle{}t care what it is), you can use {\ttfamily V\+Error.\+has\+Cause\+With\+Name(err, name)}.

If a vanilla error or a non-\/\+V\+Error error is passed in, then there is no cause chain to traverse. In this scenario, the function will check the {\ttfamily name} property of only {\ttfamily err}.

\subsubsection*{{\ttfamily V\+Error.\+has\+Cause\+With\+Name(err, name)}}

Returns true if and only if {\ttfamily V\+Error.\+find\+Cause\+By\+Name(err, name)} would return a non-\/null value. This essentially determines whether {\ttfamily err} has any cause in its cause chain that has name {\ttfamily name}.

\subsubsection*{{\ttfamily V\+Error.\+error\+From\+List(errors)}}

Given an array of Error objects (possibly empty), return a single error representing the whole collection of errors. If the list has\+:


\begin{DoxyItemize}
\item 0 elements, returns {\ttfamily null}
\item 1 element, returns the sole error
\item more than 1 element, returns a Multi\+Error referencing the whole list
\end{DoxyItemize}

This is useful for cases where an operation may produce any number of errors, and you ultimately want to implement the usual {\ttfamily callback(err)} pattern. You can accumulate the errors in an array and then invoke {\ttfamily callback(V\+Error.\+error\+From\+List(errors))} when the operation is complete.

\subsubsection*{{\ttfamily V\+Error.\+error\+For\+Each(err, func)}}

Convenience function for iterating an error that may itself be a Multi\+Error.

In all cases, {\ttfamily err} must be an Error. If {\ttfamily err} is a Multi\+Error, then {\ttfamily func} is invoked as {\ttfamily func(error\+N)} for each of the underlying errors of the Multi\+Error. If {\ttfamily err} is any other kind of error, {\ttfamily func} is invoked once as {\ttfamily func(err)}. In all cases, {\ttfamily func} is invoked synchronously.

This is useful for cases where an operation may produce any number of warnings that may be encapsulated with a Multi\+Error -- but may not be.

This function does not iterate an error\textquotesingle{}s cause chain.

\subsection*{Examples}

The \char`\"{}\+Demo\char`\"{} section above covers several basic cases. Here\textquotesingle{}s a more advanced case\+:


\begin{DoxyCode}
var err1 = new VError('something bad happened');
/* ... */
var err2 = new VError(\{
    'name': 'ConnectionError',
    'cause': err1,
    'info': \{
        'errno': 'ECONNREFUSED',
        'remote\_ip': '127.0.0.1',
        'port': 215
    \}
\}, 'failed to connect to "%s:%d"', '127.0.0.1', 215);

console.log(err2.message);
console.log(err2.name);
console.log(VError.info(err2));
console.log(err2.stack);
\end{DoxyCode}


This outputs\+: \begin{DoxyVerb}failed to connect to "127.0.0.1:215": something bad happened
ConnectionError
{ errno: 'ECONNREFUSED', remote_ip: '127.0.0.1', port: 215 }
ConnectionError: failed to connect to "127.0.0.1:215": something bad happened
    at Object.<anonymous> (/home/dap/node-verror/examples/info.js:5:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
\end{DoxyVerb}


Information properties are inherited up the cause chain, with values at the top of the chain overriding same-\/named values lower in the chain. To continue that example\+:


\begin{DoxyCode}
var err3 = new VError(\{
    'name': 'RequestError',
    'cause': err2,
    'info': \{
        'errno': 'EBADREQUEST'
    \}
\}, 'request failed');

console.log(err3.message);
console.log(err3.name);
console.log(VError.info(err3));
console.log(err3.stack);
\end{DoxyCode}


This outputs\+: \begin{DoxyVerb}request failed: failed to connect to "127.0.0.1:215": something bad happened
RequestError
{ errno: 'EBADREQUEST', remote_ip: '127.0.0.1', port: 215 }
RequestError: request failed: failed to connect to "127.0.0.1:215": something bad happened
    at Object.<anonymous> (/home/dap/node-verror/examples/info.js:20:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
\end{DoxyVerb}


You can also print the complete stack trace of combined {\ttfamily Error}s by using {\ttfamily V\+Error.\+full\+Stack(err).}


\begin{DoxyCode}
var err1 = new VError('something bad happened');
/* ... */
var err2 = new VError(err1, 'something really bad happened here');

console.log(VError.fullStack(err2));
\end{DoxyCode}


This outputs\+: \begin{DoxyVerb}VError: something really bad happened here: something bad happened
    at Object.<anonymous> (/home/dap/node-verror/examples/fullStack.js:5:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
caused by: VError: something bad happened
    at Object.<anonymous> (/home/dap/node-verror/examples/fullStack.js:3:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
\end{DoxyVerb}


{\ttfamily V\+Error.\+full\+Stack} is also safe to use on regular {\ttfamily Error}s, so feel free to use it whenever you need to extract the stack trace from an {\ttfamily Error}, regardless if it\textquotesingle{}s a {\ttfamily V\+Error} or not.

\section*{Reference\+: Multi\+Error}

Multi\+Error is an Error class that represents a group of Errors. This is used when you logically need to provide a single Error, but you want to preserve information about multiple underying Errors. A common case is when you execute several operations in parallel and some of them fail.

Multi\+Errors are constructed as\+:


\begin{DoxyCode}
new MultiError(error\_list)
\end{DoxyCode}


{\ttfamily error\+\_\+list} is an array of at least one {\ttfamily Error} object.

The cause of the Multi\+Error is the first error provided. None of the other {\ttfamily V\+Error} options are supported. The {\ttfamily message} for a Multi\+Error consists the {\ttfamily message} from the first error, prepended with a message indicating that there were other errors.

For example\+:


\begin{DoxyCode}
err = new MultiError([
    new Error('failed to resolve DNS name "abc.example.com"'),
    new Error('failed to resolve DNS name "def.example.com"'),
]);

console.error(err.message);
\end{DoxyCode}


outputs\+: \begin{DoxyVerb}first of 2 errors: failed to resolve DNS name "abc.example.com"
\end{DoxyVerb}


See the convenience function {\ttfamily V\+Error.\+error\+From\+List}, which is sometimes simpler to use than this constructor.

\subsection*{Public methods}

\subsubsection*{{\ttfamily errors()}}

Returns an array of the errors used to construct this Multi\+Error.

\section*{Contributing}

See separate contribution guidelines. 